### PR TITLE
raidemulator - Implement timelineTriggers support

### LINKED ISSUE #2504: bug： timeline Trigger can't modify data in raid emulator
## Description

I'm testing a set of triggers, and I found that timeline trigger can't modify data in any way. And `run`, `preRun` method are omitted. If I modify data in funxtion like `infoText` the modifition will be omitted.

## Additional information

log: 
[pure.log](https://github.com/quisquous/cactbot/files/6023557/pure.log)

trigger:
```JS
Options.Triggers.push({
  zoneId: ZoneId.TheEpicOfAlexanderUltimate,
  timelineTriggers: [
    {
      id: 'TEA 子言 时停阶段',
      regex: /Propeller Wind/,
      // delaySeconds: 20,
      infoText: (data, _, output) => {
        data.userPhase = 'Temporal Stasis';
// modify data here and it doesn't works,
// weather in `run(data)` or `preRun(data)` in later trigger infomation
// There's no such property or any other modification I made here
        console.log(data.userPhase); // output 'Temporal Stasis'
        return '提前进入时停阶段，反正中间也没啥东西'; // but this works fine and output correctly
      },
    },
  ],
});

```

### PR DESCRIPTION
**Pull request by valarnin**
This PR fixes #2504 by supporting `timelineTriggers` during encounter analysis.

This is a first pass. It's functional but causes a lot of DOM updates (due to the timeline events actually firing during analysis) which makes the initial encounter load slightly slower.

I'm not sure if it's worth the effort of fixing this, I can barely tell a difference on my hardware so I'd prefer if someone with slower hardware can test and let me know how much the performance impact is vs the current `main` code.

### CODE REVIEW

**Comment by quisquous** [comment]
Sorry, I haven't forgotten about this, but just haven't had enough time to take a closer look at it.

**Comment by valarnin** [comment]
> Sorry, I haven't forgotten about this, but just haven't had enough time to take a closer look at it.

No problem, this isn't holding up the rest of the items in the "needs improvement" issue, I injured myself last Saturday and that's put a damper on my ability to work on this for the next week or two.

File: ui/raidboss/emulator/overrides/RaidEmulatorTimelineController.js [hunk 1]
```diff
@@ -43,7 +43,10 @@ export default class RaidEmulatorTimelineController extends TimelineController {
     e.detail.logs.forEach((line) => {
       this.activeTimeline.emulatedTimeOffset = line.offset;
       this.ui.emulatedTimeOffset = line.offset;
+      this.activeTimeline.timebase =
+        new Date() - (line.offset - this.emulator.currentEncounter.encounter.initialOffset);
```
Comment (quisquous) [inline ui/raidboss/emulator/overrides/RaidEmulatorTimelineController.js:47]: Maybe this is a continuation of the suppressSeconds conversation from the other patch, but it is weird to me to ever see `new Date()` in any emulator code.  My expectation is that time should be some "virtual time" entirely controlled by the emulator.

It looks like `new Date()` is used in `SyncTo` and `_OnUpdateTimer()`.

What if:
* `activetimeline.OnLogLine` also took a current time parameter (the `SyncTo` case)
* `_OnUpdateTimer` also took a current time parameter
* update `timeline.js` to pass `new Date()` to the callers of these two functions
* Pass the log line time to `OnLogLine`, which will set the timebase for you
* Call `_OnUpdateTimer` with the current log line time as well

**Review by quisquous — COMMENTED** [review]
Performance-wise this seems fine to me.  Thanks for implementing it.

I had a couple of code questions (sorry):

File: ui/raidboss/emulator/data/AnalyzedEncounter.js [hunk 2]
```diff
@@ -78,6 +81,32 @@ export default class AnalyzedEncounter extends EventBus {
...
+      popupText.OnTrigger(trigger, matches);
+
+      await delayPromise;
+      await promisePromise;
+      const triggerHelper = await runPromise;
+
+      popupText.currentTriggerStatus.finalData = EmulatorCommon.cloneData(popupText.data);
+
+      popupText.callback(
+          this.encounter.logLines[currentLogIndex],
```
[the remark this answers is not in the document]
Comment (valarnin) [reply ui/raidboss/emulator/data/AnalyzedEncounter.js:106]: The callback definition immediately below it uses `log.timestamp` to calculate when the trigger was resolved in the pull.

```js
    popupText.callback = (log, triggerHelper, currentTriggerStatus, finalData) => {
      this.perspectives[ID].triggers.push({
        triggerHelper: triggerHelper,
        status: currentTriggerStatus,
        logLine: log,
        resolvedOffset: (log.timestamp - this.encounter.startTimestamp) +
          (currentTriggerStatus.delay * 1000),
      });
    };
```

In addition, `EmulatedPartyInfo.js`'s uses the timestamp of the log line for calculations.

File: ui/raidboss/emulator/overrides/RaidEmulatorTimelineController.js (hunk 1 above)
Comment (valarnin) [reply ui/raidboss/emulator/overrides/RaidEmulatorTimelineController.js:47]: Any time there's a `new Date` call that's not isolated, I have to account for it with extra logic like this in emulator. That's why I was suggesting that calls to `new Date` in raidboss be replaced with calls to a class function `getDate` or something that could be overridden in emulator as a global "return the current log line's timestamp" logic.

Comment (quisquous) [reply ui/raidboss/emulator/overrides/RaidEmulatorTimelineController.js:47]: I agree that `new Date()` needs to be abstracted.  In general, I prefer passing in the time explicitly to functions vs the implicit overriding of a functions.  It means that internal functions can't call `getDate` repeatedly (which is usually an anti-pattern for a processing function) and also makes it more clear that the date is being controlled explicitly externally and may not behave monotically.

Comment (valarnin) [reply ui/raidboss/emulator/overrides/RaidEmulatorTimelineController.js:47]: I think this would belong in a separate PR, so the question becomes should this PR wait until that change, or should this be merged as-is and the date stuff be a follow up PR?

Comment (quisquous) [reply ui/raidboss/emulator/overrides/RaidEmulatorTimelineController.js:47]: Oops, somehow I lost track of responding to this comment.  Thanks for submitting the other PR, you read my mind.  :)

**Comment by valarnin** [comment]
@quisquous I have updated this PR to take into account the changes to the way date is passed. Please re-review. I'd like to get started on converting emulator to typescript as soon as I get the remaining two outstanding issues resolved, which I'll do in my next PR after this one is merged.

**Comment by quisquous** [comment]
Thanks for fixing up the time issues.  This makes this patch feel much better to me.
