### PR TITLE
jobs: Refactor and fix food timer

### LINKED ISSUE #4032: [Jobs] Cheese icon is always showing
## Description

Cheese icon is always shown. No matter the setting.
image

## Additional information

Info: Jobs: BrowserConsole: Uncaught TypeError: Cannot read properties of undefined (reading 'foodBuffTimer') (Source: file:///D:/Programs/Advanced%20Combat%20Tracker/Overlay/cactbot/ui/jobs/jobs.bundle.js, Line: 34088)

### PR DESCRIPTION
**Pull request by Echoring**
- Fix food timer by split `_updateFoodBuff` into `_showFoodBuff`, `_canShowFoodBuff` and `_shouldShowFoodBuff`
`_canShowFoodBuff` decides if cheese icon can show now.
`_shouldShowFoodBuff` decides show cheese icon now or later if it can show.
`_showFoodBuff` directly make cheese icon shown.
- Fix a bug that in-combat status not updated soon enough.

Fixes #4032

Known issues: <del>bug within a bug</del>
1. When changing zone, a fake "gainEffect" log with fake duration will update food timer incorrectly.
2. <del>When you dispel your food buff, food timer will not update.</del>
3. When using a max level job in leveling dungeons, cheese icon still showing.

Unrelated issues found in debug: <del>bug within a bug within a bug</del>
1. When AOE combo action hit nothing, `comboTimer` still considers combo established.
2. In patch 6.1, some 2.0 dungeons are remaked and got a new `ZoneID`, which makes CN/KO version cannot match these dungeons.

### CODE REVIEW

File: ui/jobs/components/index.ts [hunk 1]
```diff
@@ -156,14 +157,8 @@ export class ComponentManager {
...
     this.player.on('level', (level, prevLevel) => {
-      if (level - prevLevel) {
-        this.bars._updateFoodBuff({
-          inCombat: this.component?.inCombat ?? false,
-          foodBuffExpiresTimeMs: this.foodBuffExpiresTimeMs,
-          foodBuffTimer: this.foodBuffTimer,
-          contentType: this.contentType,
-        });
-      }
+      if (level - prevLevel)
```
Comment (quisquous) [inline ui/jobs/components/index.ts:160]: I know this code was here before, but I think it means:
```suggestion
      if (level !== prevLevel)
```

File: ui/jobs/components/index.ts [hunk 2]
```diff
@@ -376,4 +357,33 @@ export class ComponentManager {
     )
       this.bars.setJobsContainerVisibility(false);
   }
+
+  private _shouldShowFoodBuff(): void {
```
Comment (quisquous) [inline ui/jobs/components/index.ts:361]: Could you call this `_updateFoodBuff` or `_updateFoodBuffDisplay` or something?

Mostly my preference is that if a function starts with "should" then it's a small function that returns a boolean, e.g. shouldShowFoodBuff returns true or false, whether or not it should show.  And so the naming is a little bit confusing to me.

File: ui/jobs/components/index.ts [hunk 3]
```diff
@@ -376,4 +357,33 @@ export class ComponentManager {
...
+      this.bars._showFoodBuff(true);
+    } else {
+      this.bars._showFoodBuff(false);
+      this.foodBuffTimer = window.setTimeout(this._shouldShowFoodBuff.bind(this), showMs);
+    }
+  }
+
+  private _canShowFoodBuff(): boolean {
+    return (
+      Boolean(this.options.HideWellFedAboveSeconds) &&
```
Comment (quisquous) [inline ui/jobs/components/index.ts:383]:
```suggestion
      this.options.HideWellFedAboveSeconds !== 0 &&
```

File: ui/jobs/components/index.ts [hunk 4]
```diff
@@ -376,4 +357,33 @@ export class ComponentManager {
...
+    const showMs = showAtMs - Date.now();
+
+    window.clearTimeout(this.foodBuffTimer);
+    this.foodBuffTimer = 0;
+
+    if (showMs <= 0) {
+      this.bars._showFoodBuff(true);
+    } else {
+      this.bars._showFoodBuff(false);
+      this.foodBuffTimer = window.setTimeout(this._shouldShowFoodBuff.bind(this), showMs);
```
Comment (quisquous) [inline ui/jobs/components/index.ts:377]: I know this was here before, but this should probably use an arrow function instead of a `bind`:
```suggestion
      this.foodBuffTimer = window.setTimeout(() => this._shouldShowFoodBuff(), showMs);
```

**Review by quisquous — COMMENTED** [review]
Thank you for the fix and for finding a bunch of bugs! I'll take a look at the zoning+Well Fed issue and see if I can understand what's happening there and maybe file an ffxiv act plugin bug if needed.

**Comment by quisquous** [comment]
> In patch 6.1, some 2.0 dungeons are remaked and got a new ZoneID, which makes CN/KO version cannot match these dungeons.

I think for now we can ignore this, as the 6.0 Korean patch is happening in a few days.  If more dungeons get remade, I'll try to remember to add old entries for them like I do with the unreals that get removed.

**Comment by Akurosia** [comment]
small sidenote, KO 6.0 will patch is tomorrow the 10th Mai

**Comment by Echoring** [comment]
Done. Also fixed dispel wellFed issue.
As for issue of level, I believe there are a related block lost in previous refactor, maybe fix them in later pr.

**Comment by quisquous** [comment]
Thanks again for taking the time to fix this (and finding other bugs)!  Much appreciated.  :)
