### PR TITLE
util: Fix encounter_tools encounter listing

### LINKED ISSUE #4493: make_timeline.ts formatting is hard to read
Maybe the padding is wrong? (not urgent, but cc-ing @JLGarber just fyi)

```
$ ts-node util/logtools/make_timeline.ts -f /d/ffxivlogs/log/Network*20220517.2022*.log -lf
2022-05-18
2022-05-17
  1)  09:06:25.642 8m Ultima's Bane (Unreal)    [Win]
  2)  09:19:11.532 7m Ultima's Bane (Unreal)    [Wipe]
  3)  09:26:41.336 7m Ultima's Bane (Unreal)    [Win]

                        ~Alexander - The Eyes of the Creator (Savage)~
2022-05-17
  4)  09:54:35.000 19s Life Support                        [Unseal]
  5)  09:56:30.000 18s Life Support                        [Unseal]
  6)  09:57:52.000 18s Life Support                        [Unseal]
  7)  09:59:23.000 16s Life Support                        [Unseal]
  8)  10:00:41.000 17s Life Support                        [Unseal]
  9)  10:02:01.000 26s Life Support                        [Zone Change]
  10)  10:03:17.000 16s Life Support                        [Unseal]
  11)  10:04:38.000 17s Life Support                        [Unseal]
  12)  10:05:56.000 16s Life Support                        [Unseal]
  13)  10:07:13.000 19s Life Support                        [Unseal]
  14)  10:09:02.000 17s Life Support                        [Unseal]
  15)  10:10:31.000 18s Life Support                        [Unseal]
  16)  10:14:55.000 16s Life Support                        [Unseal]
  17)  10:16:26.000 18s Life Support                        [Unseal]
  18)  10:17:47.000 19s Life Support                        [Unseal]
  19)  10:19:06.000 16s Life Support                        [Unseal]
  20)  10:20:45.000 23s Life Support                        [Unseal]
  21)  10:22:14.000 20s Life Support                        [Unseal]
  22)  10:23:35.000 18s Life Support                        [Unseal]
  23)  10:25:05.000 19s Life Support                        [Unseal]
  24)  10:26:26.000 18s Life Support                        [Unseal]
  25)  10:32:56.884 20s the Bowl of Embers (Hard)  [Win]
  26)  10:33:43.922 29s the Howling Eye (Hard)    [Win]
  27)  10:34:39.633 48s the Navel (Hard)                [Win]
  28)  10:35:53.101 1m Thornmarch (Hard)              [Win]
  29)  10:37:40.679 1m the Whorleater (Hard)      [Win]
  30)  10:39:26.179 32s the Striking Tree (Hard)  [Win]
  31)  10:40:29.008 9s the Akh Afah Amphitheatre (Hard)  [Win]
  32)  10:41:16.520 16s Thok ast Thok (Hard)        [Win]
  33)  10:42:09.039 3m the Limitless Blue (Hard)  [Win]
  34)  10:46:13.143 1m Containment Bay (S1T7)    [Win]
  35)  10:48:20.329 1m Containment Bay (P1T6)    [Win]
  36)  10:49:56.506 59s Containment Bay (Z1T9)    [Win]

                        ~Aglaia~
2022-05-17
  37)  11:05:41.000 4m Ingenuity's Foothold        [Unseal]
  38)  11:11:18.000 1m The Path                                [Unseal]
  39)  11:13:56.000 4m The Monument to Destruction  [Unseal]
  40)  11:19:33.000 1m The Endless City                [Unseal]
  41)  11:21:44.000 5m The Circle of Inquiry      [Unseal]
  42)  11:28:28.000 8m The Twin Halls                    [Unseal]
  43)  15:54:54.987 28m Mist                                        [Zone Change]
2022-05-18
  44)  18:03:23.063 5m Dragonsong's Reprise (Ultimate)  [Wipe]
  45)  18:09:21.835 7m Dragonsong's Reprise (Ultimate)  [Wipe]
  46)  18:25:24.535 59s Dragonsong's Reprise (Ultimate)  [Wipe]
  47)  18:26:51.114 5m Dragonsong's Reprise (Ultimate)  [Wipe]
  48)  18:33:08.111 2m Dragonsong's Reprise (Ultimate)  [Wipe]
  49)  18:35:38.284 7m Dragonsong's Reprise (Ultimate)  [Wipe]
  50)  18:50:57.518 4m Dragonsong's Reprise (Ultimate)  [Wipe]
  51)  18:55:55.208 1m Dragonsong's Reprise (Ultimate)  [Wipe]
  52)  18:57:24.513 9s Dragonsong's Reprise (Ultimate)  [Wipe]
  53)  19:02:50.142 4m Dragonsong's Reprise (Ultimate)  [Wipe]
  54)  19:08:09.093 2m Dragonsong's Reprise (Ultimate)  [Wipe]
  55)  19:11:16.204 4m Dragonsong's Reprise (Ultimate)  [Wipe]
  56)  19:16:09.897 6m Dragonsong's Reprise (Ultimate)  [Wipe]
  57)  19:30:15.905 7m Dragonsong's Reprise (Ultimate)  [Wipe]
  58)  19:37:44.354 3m Dragonsong's Reprise (Ultimate)  [Wipe]
  59)  19:42:02.187 7m Dragonsong's Reprise (Ultimate)  [Wipe]
  60)  19:55:38.600 2m Dragonsong's Reprise (Ultimate)  [Wipe]
  61)  19:58:34.463 7m Dragonsong's Reprise (Ultimate)  [Wipe]
  62)  20:23:21.218 3m Empyreum                                [Zone Change]
  63)  20:26:35.962 1m Dragonsong's Reprise (Ultimate)  [Wipe]
  64)  20:28:05.051 53s Dragonsong's Reprise (Ultimate)  [Wipe]
  65)  20:29:28.435 2m Dragonsong's Reprise (Ultimate)  [Wipe]
  66)  20:33:04.744 1m Dragonsong's Reprise (Ultimate)  [Wipe]
  67)  20:34:30.523 7m Dragonsong's Reprise (Ultimate)  [Wipe]
  68)  20:49:40.466 2m Dragonsong's Reprise (Ultimate)  [Wipe]
  69)  20:52:46.834 1m Dragonsong's Reprise (Ultimate)  [Wipe]
  70)  20:54:22.846 1m Dragonsong's Reprise (Ultimate)  [Wipe]
  71)  20:56:02.120 2m Dragonsong's Reprise (Ultimate)  [Wipe]
  72)  20:58:52.517 4m Dragonsong's Reprise (Ultimate)  [Wipe]
  73)  21:05:15.073 5m Dragonsong's Reprise (Ultimate)  [Wipe]
  74)  21:13:20.485 2m Dragonsong's Reprise (Ultimate)  [Wipe]
  75)  21:17:08.730 6m Dragonsong's Reprise (Ultimate)  [Wipe]
  76)  21:26:34.196 2m Dragonsong's Reprise (Ultimate)  [Wipe]
  77)  21:29:30.827 2m Dragonsong's Reprise (Ultimate)  [Wipe]
  78)  21:32:19.529 1m Dragonsong's Reprise (Ultimate)  [Wipe]
  79)  21:33:56.527 8m Dragonsong's Reprise (Ultimate)  [Wipe]
  80)  21:51:39.844 2m Dragonsong's Reprise (Ultimate)  [Wipe]
  81)  21:54:29.073 2m Dragonsong's Reprise (Ultimate)  [Wipe]
  82)  21:57:06.496 7m Dragonsong's Reprise (Ultimate)  [Wipe]
```

I know it's a different tool entirely, but for comparison:
```
$ python util/make_timeline.py -f /d/ffxivlogs/log/Network*20220517.2022*.log -lf
01. 09:06:25.642 | 09:14:49.503 | 08:23 | Ultima's Bane (Unreal)
02. 09:19:32.392 | 09:26:14.815 | 06:42 | Ultima's Bane (Unreal)
03. 09:26:41.336 | 09:34:05.623 | 07:24 | Ultima's Bane (Unreal)
04. 10:35:53.101 | 10:37:09.140 | 01:16 | Thornmarch (Hard)
05. 10:37:40.679 | 10:38:42.178 | 01:01 | The Whorleater (Hard)
06. 10:42:17.060 | 10:45:40.114 | 03:23 | The Limitless Blue (Hard)
07. 10:46:13.143 | 10:47:55.170 | 01:42 | Containment Bay S1T7
08. 10:48:20.329 | 10:49:30.025 | 01:09 | Containment Bay P1T6
09. 11:05:41.000 | 11:10:32.000 | 04:51 | Ingenuity's Foothold
10. 11:11:18.000 | 11:13:15.000 | 01:57 | The Path
11. 11:13:56.000 | 11:18:49.000 | 04:53 | The Monument to Destruction
12. 11:19:33.000 | 11:21:14.000 | 01:41 | The Endless City
13. 11:21:44.000 | 11:27:32.000 | 05:48 | The Circle of Inquiry
14. 11:28:28.000 | 11:36:36.833 | 08:08 | The Twin Halls
15. 18:06:12.223 | 18:08:55.720 | 02:43 | Dragonsong's Reprise (Ultimate)
16. 18:09:21.835 | 18:16:28.397 | 07:06 | Dragonsong's Reprise (Ultimate)
17. 18:26:51.114 | 18:32:15.742 | 05:24 | Dragonsong's Reprise (Ultimate)
18. 18:33:08.111 | 18:35:13.417 | 02:05 | Dragonsong's Reprise (Ultimate)
19. 18:35:38.284 | 18:42:45.966 | 07:07 | Dragonsong's Reprise (Ultimate)
20. 18:50:57.518 | 18:55:30.963 | 04:33 | Dragonsong's Reprise (Ultimate)
21. 18:55:55.208 | 18:57:05.357 | 01:10 | Dragonsong's Reprise (Ultimate)
22. 19:02:50.142 | 19:07:37.788 | 04:47 | Dragonsong's Reprise (Ultimate)
23. 19:08:09.093 | 19:10:40.341 | 02:31 | Dragonsong's Reprise (Ultimate)
24. 19:11:16.204 | 19:15:43.340 | 04:27 | Dragonsong's Reprise (Ultimate)
25. 19:16:09.897 | 19:23:07.173 | 06:57 | Dragonsong's Reprise (Ultimate)
26. 19:30:15.905 | 19:37:20.353 | 07:04 | Dragonsong's Reprise (Ultimate)
27. 19:38:30.818 | 19:40:51.496 | 02:20 | Dragonsong's Reprise (Ultimate)
28. 19:42:02.187 | 19:49:10.189 | 07:08 | Dragonsong's Reprise (Ultimate)
29. 19:55:38.600 | 19:58:09.296 | 02:30 | Dragonsong's Reprise (Ultimate)
30. 19:58:34.463 | 20:05:44.779 | 07:10 | Dragonsong's Reprise (Ultimate)
31. 20:29:28.435 | 20:32:10.748 | 02:42 | Dragonsong's Reprise (Ultimate)
32. 20:33:04.744 | 20:34:05.169 | 01:00 | Dragonsong's Reprise (Ultimate)
33. 20:34:30.523 | 20:41:38.229 | 07:07 | Dragonsong's Reprise (Ultimate)
34. 20:49:40.466 | 20:52:00.903 | 02:20 | Dragonsong's Reprise (Ultimate)
35. 20:52:46.834 | 20:53:58.480 | 01:11 | Dragonsong's Reprise (Ultimate)
36. 20:54:22.846 | 20:55:36.723 | 01:13 | Dragonsong's Reprise (Ultimate)
37. 20:56:02.120 | 20:58:25.457 | 02:23 | Dragonsong's Reprise (Ultimate)
38. 20:58:52.517 | 21:03:37.433 | 04:44 | Dragonsong's Reprise (Ultimate)
39. 21:05:15.073 | 21:10:38.945 | 05:23 | Dragonsong's Reprise (Ultimate)
40. 21:13:20.485 | 21:15:51.936 | 02:31 | Dragonsong's Reprise (Ultimate)
41. 21:17:08.730 | 21:23:57.227 | 06:48 | Dragonsong's Reprise (Ultimate)
42. 21:26:34.196 | 21:28:55.224 | 02:21 | Dragonsong's Reprise (Ultimate)
43. 21:29:30.827 | 21:31:55.002 | 02:24 | Dragonsong's Reprise (Ultimate)
44. 21:32:19.529 | 21:33:32.616 | 01:13 | Dragonsong's Reprise (Ultimate)
45. 21:33:56.527 | 21:42:07.316 | 08:10 | Dragonsong's Reprise (Ultimate)
46. 21:51:39.844 | 21:54:05.022 | 02:25 | Dragonsong's Reprise (Ultimate)
47. 21:54:29.073 | 21:56:42.785 | 02:13 | Dragonsong's Reprise (Ultimate)
48. 21:57:06.496 | 22:04:09.718 | 07:03 | Dragonsong's Reprise (Ultimate)
```

### PR DESCRIPTION
**Pull request by JLGarber**
```
2022-04-25
2022-04-24
   1)  16:56:11.436 |  2m | Thavnair                             [Zone Change]
   2)  17:25:55.837 |  1m | Eden's Gate: Descent                 [Wipe]
   3)  17:51:32.543 |  6m | Eden's Gate: Descent                 [Win]
   4)  18:25:11.796 |  7m | Alexander - The Soul of the Creator  [Win]
   5)  18:43:18.817 | 83m | Radz-at-Han                          [Zone Change]
2022-04-25
   6)  20:12:08.257 |  6m | Thavnair                             [Zone Change]

                        ~The Temple of the Fist~
2022-04-25
   7)  20:21:50.000 |  1m | Tourmaline Pond                      [Unseal]
   8)  20:27:17.000 |  2m | Harmony                              [Unseal]
   9)  20:32:32.000 |  3m | Guidance                             [Unseal]
  10)  20:42:06.077 | 62m | Radz-at-Han                          [Zone Change]

                        ~Aglaia~
2022-04-25
  11)  21:45:04.000 |  5m | Ingenuity's Foothold                 [Unseal]
  12)  21:51:07.000 |  2m | The Path                             [Unseal]
  13)  21:53:50.000 |  5m | The Monument to Destruction          [Unseal]
  14)  21:59:48.000 |  1m | The Endless City                     [Unseal]
  15)  22:02:01.000 |  6m | The Circle of Inquiry                [Unseal]
  16)  22:09:32.000 |  8m | The Twin Halls                       [Unseal]
  17)  23:05:08.000 |  1m | The command chamber                  [Unseal]
  18)  23:16:28.000 |  2m | The Laboratorium Primum              [Unseal]
  19)  23:25:53.000 |  3m | The Echelon                          [Unseal]
  ```

Primarily this was caused by forgetting that `padStart/padEnd` implicitly contain a `max(currentLength, outputLength)`. While here I also added column separators. This should resolve #4493.

### CODE REVIEW

**Comment by JLGarber** [comment]
Okay, this produces:

```
┌───────┬──────────────┬────────────────┬──────────┬───────────────────────────────────────┬───────────────────────────────────────┬───────────────┐
│ Index │  Start Date  │   Start Time   │ Duration │               Zone Name               │            Encounter Name             │   End Type    │
├───────┼──────────────┼────────────────┼──────────┼───────────────────────────────────────┼───────────────────────────────────────┼───────────────┤
│   1   │  2022-04-24  │  16:56:11.436  │    2m    │               Thavnair                │               Thavnair                │  Zone Change  │
│   2   │  2022-04-24  │  17:25:55.837  │    1m    │         Eden s Gate: Descent          │         Eden s Gate: Descent          │     Wipe      │
│   3   │  2022-04-24  │  17:51:32.543  │    6m    │         Eden s Gate: Descent          │         Eden s Gate: Descent          │      Win      │
│   4   │  2022-04-24  │  18:25:11.796  │    7m    │  Alexander - The Soul of the Creator  │  Alexander - The Soul of the Creator  │      Win      │
│   5   │  2022-04-24  │  18:43:18.817  │   83m    │              Radz-at-Han              │              Radz-at-Han              │  Zone Change  │
│   6   │  2022-04-25  │  20:12:08.257  │    6m    │               Thavnair                │               Thavnair                │  Zone Change  │
│   7   │  2022-04-25  │  20:21:50.000  │    1m    │        The Temple of the Fist         │            Tourmaline Pond            │    Unseal     │
│   8   │  2022-04-25  │  20:27:17.000  │    2m    │        The Temple of the Fist         │                Harmony                │    Unseal     │
│   9   │  2022-04-25  │  20:32:32.000  │    3m    │        The Temple of the Fist         │               Guidance                │    Unseal     │
│  10   │  2022-04-25  │  20:42:06.077  │   62m    │              Radz-at-Han              │              Radz-at-Han              │  Zone Change  │
│  11   │  2022-04-25  │  21:45:04.000  │    5m    │                Aglaia                 │         Ingenuity s Foothold          │    Unseal     │
│  12   │  2022-04-25  │  21:51:07.000  │    2m    │                Aglaia                 │               The Path                │    Unseal     │
│  13   │  2022-04-25  │  21:53:50.000  │    5m    │                Aglaia                 │      The Monument to Destruction      │    Unseal     │
│  14   │  2022-04-25  │  21:59:48.000  │    1m    │                Aglaia                 │           The Endless City            │    Unseal     │
│  15   │  2022-04-25  │  22:02:01.000  │    6m    │                Aglaia                 │         The Circle of Inquiry         │    Unseal     │
│  16   │  2022-04-25  │  22:09:32.000  │    8m    │                Aglaia                 │            The Twin Halls             │    Unseal     │
│  17   │  2022-04-25  │  23:05:08.000  │    1m    │            the Praetorium             │          The command chamber          │    Unseal     │
│  18   │  2022-04-25  │  23:16:28.000  │    2m    │            the Praetorium             │        The Laboratorium Primum        │    Unseal     │
│  19   │  2022-04-25  │  23:25:53.000  │    3m    │            the Praetorium             │              The Echelon              │    Unseal     │
└───────┴──────────────┴────────────────┴──────────┴───────────────────────────────────────┴───────────────────────────────────────┴───────────────┘
```

Unfortunately this does strip real apostrophes from within words. I can't regex tonight so I'll just leave it here, but it *should* be a simple enough fix to strip only bounding single quotes.

**Comment by JLGarber** [comment]
After consuming  (too much) pizza I was able to summon enough brain to create a monstrosity. But it works:
```
┌───────┬──────────────┬────────────────┬──────────┬───────────────────────────────────────┬───────────────────────────────────────┬───────────────┐
│ Index │  Start Date  │   Start Time   │ Duration │               Zone Name               │            Encounter Name             │   End Type    │
├───────┼──────────────┼────────────────┼──────────┼───────────────────────────────────────┼───────────────────────────────────────┼───────────────┤
│   1   │  2022-04-24  │  16:56:11.436  │    2m    │               Thavnair                │               Thavnair                │  Zone Change  │
│   2   │  2022-04-24  │  17:25:55.837  │    1m    │         Eden's Gate: Descent          │         Eden's Gate: Descent          │     Wipe      │
│   3   │  2022-04-24  │  17:51:32.543  │    6m    │         Eden's Gate: Descent          │         Eden's Gate: Descent          │      Win      │
│   4   │  2022-04-24  │  18:25:11.796  │    7m    │  Alexander - The Soul of the Creator  │  Alexander - The Soul of the Creator  │      Win      │
│   5   │  2022-04-24  │  18:43:18.817  │   83m    │              Radz-at-Han              │              Radz-at-Han              │  Zone Change  │
│   6   │  2022-04-25  │  20:12:08.257  │    6m    │               Thavnair                │               Thavnair                │  Zone Change  │
│   7   │  2022-04-25  │  20:21:50.000  │    1m    │        The Temple of the Fist         │            Tourmaline Pond            │    Unseal     │
│   8   │  2022-04-25  │  20:27:17.000  │    2m    │        The Temple of the Fist         │                Harmony                │    Unseal     │
│   9   │  2022-04-25  │  20:32:32.000  │    3m    │        The Temple of the Fist         │               Guidance                │    Unseal     │
│  10   │  2022-04-25  │  20:42:06.077  │   62m    │              Radz-at-Han              │              Radz-at-Han              │  Zone Change  │
│  11   │  2022-04-25  │  21:45:04.000  │    5m    │                Aglaia                 │         Ingenuity's Foothold          │    Unseal     │
│  12   │  2022-04-25  │  21:51:07.000  │    2m    │                Aglaia                 │               The Path                │    Unseal     │
│  13   │  2022-04-25  │  21:53:50.000  │    5m    │                Aglaia                 │      The Monument to Destruction      │    Unseal     │
│  14   │  2022-04-25  │  21:59:48.000  │    1m    │                Aglaia                 │           The Endless City            │    Unseal     │
│  15   │  2022-04-25  │  22:02:01.000  │    6m    │                Aglaia                 │         The Circle of Inquiry         │    Unseal     │
│  16   │  2022-04-25  │  22:09:32.000  │    8m    │                Aglaia                 │            The Twin Halls             │    Unseal     │
│  17   │  2022-04-25  │  23:05:08.000  │    1m    │            the Praetorium             │          The command chamber          │    Unseal     │
│  18   │  2022-04-25  │  23:16:28.000  │    2m    │            the Praetorium             │        The Laboratorium Primum        │    Unseal     │
│  19   │  2022-04-25  │  23:25:53.000  │    3m    │            the Praetorium             │              The Echelon              │    Unseal     │
└───────┴──────────────┴────────────────┴──────────┴───────────────────────────────────────┴───────────────────────────────────────┴───────────────┘
```

File: util/logtools/encounter_tools.ts [hunk 1]
```diff
@@ -24,6 +27,29 @@ type FightEncInfo = ZoneEncInfo & {
...
+  const logger = new Console({ stdout: ts });
+  logger.table(data);
+  const tsRead = ts.read() as Buffer;
+  let result = '';
+  for (const row of tsRead.toString().split(/[\r\n]+/)) {
+    let r = row.replace(/[^┬]*┬/, '┌');
+    r = r.replace(/^├─*┼/, '├');
+    r = r.replace(/│[^│]*/, '');
+    r = r.replace(/^└─*┴/, '└');
+    r = r.replace(/(\s['"]|['"]\s)/g, '  ');
```
Comment (quisquous) [inline util/logtools/encounter_tools.ts:47]: Hmm, I don't think this will work for trailing apostrophes, e.g. "Hells' Lid".  What about `replace(/['"](\s+|)/, ' $1')` and `replace(/(|\s+)['"]/, '$1 ')`

Comment (JLGarber) [reply util/logtools/encounter_tools.ts]: Very glad regex101 exists, I wouldn't have figured out the Unicode issue with this otherwise!
