### PR TITLE
fix config outputString

### LINKED ISSUE #3090: TS version popup-text breaks current trigger
```text
[2021/6/14 20:32:15] Info: 时间轴: BrowserConsole: Trigger UCU Morn Afah has invalid outputString mornAfahPlayer. (Source: file:///C:/Users/Trim21/Desktop/act/cactbot/dist/ui/raidboss/raidboss.bundle.js, Line: 13665)
[2021/6/14 20:32:23] Info: 时间轴: BrowserConsole: Trigger UCU Akh Morn has invalid outputString text. (Source: file:///C:/Users/Trim21/Desktop/act/cactbot/dist/ui/raidboss/raidboss.bundle.js, Line: 13665)
[2021/6/14 20:32:35] Info: 时间轴: BrowserConsole: Trigger UCU Exaflare has invalid outputString text. (Source: file:///C:/Users/Trim21/Desktop/act/cactbot/dist/ui/raidboss/raidboss.bundle.js, Line: 13665)
[2021/6/14 20:32:55] Info: 时间轴: BrowserConsole: Trigger UCU Akh Morn has invalid outputString text. (Source: file:///C:/Users/Trim21/Desktop/act/cactbot/dist/ui/raidboss/raidboss.bundle.js, Line: 13665)
[2021/6/14 20:33:10] Info: 时间轴: BrowserConsole: Trigger UCU Morn Afah has invalid outputString mornAfahPlayer. (Source: file:///C:/Users/Trim21/Desktop/act/cactbot/dist/ui/raidboss/raidboss.bundle.js, Line: 13665)
[2021/6/14 20:33:24] Info: 时间轴: BrowserConsole: Trigger UCU Exaflare has invalid outputString text. (Source: file:///C:/Users/Trim21/Desktop/act/cactbot/dist/ui/raidboss/raidboss.bundle.js, Line: 13665)
[2021/6/14 20:33:43] Info: 时间轴: BrowserConsole: Trigger UCU Morn Afah has invalid outputString mornAfahPlayer. (Source: file:///C:/Users/Trim21/Desktop/act/cactbot/dist/ui/raidboss/raidboss.bundle.js, Line: 13665)
[2021/6/14 20:33:58] Info: 时间轴: BrowserConsole: Trigger UCU Akh Morn has invalid outputString text. (Source: file:///C:/Users/Trim21/Desktop/act/cactbot/dist/ui/raidboss/raidboss.bundle.js, Line: 13665)
[2021/6/14 20:34:14] Info: 时间轴: BrowserConsole: Trigger UCU Exaflare has invalid outputString text. (Source: file:///C:/Users/Trim21/Desktop/act/cactbot/dist/ui/raidboss/raidboss.bundle.js, Line: 13665)
[2021/6/14 20:34:33] Info: 时间轴: BrowserConsole: Trigger UCU Morn Afah has invalid outputString mornAfahPlayer. (Source: file:///C:/Users/Trim21/Desktop/act/cactbot/dist/ui/raidboss/raidboss.bundle.js, Line: 13665)
[2021/6/14 20:34:47] Info: 时间轴: BrowserConsole: Trigger UCU Akh Morn has invalid outputString text. (Source: file:///C:/Users/Trim21/Desktop/act/cactbot/dist/ui/raidboss/raidboss.bundle.js, Line: 13665)
[2021/6/14 20:35:05] Info: 时间轴: BrowserConsole: Trigger UCU Exaflare has invalid outputString text. (Source: file:///C:/Users/Trim21/Desktop/act/cactbot/dist/ui/raidboss/raidboss.bundle.js, Line: 13665)
[2021/6/14 20:35:24] Info: 时间轴: BrowserConsole: Trigger UCU Morn Afah has invalid outputString mornAfahPlayer. (Source: file:///C:/Users/Trim21/Desktop/act/cactbot/dist/ui/raidboss/raidboss.bundle.js, Line: 13665)
```

There is a previous error in log, didn't know if they are relative.

re-produecd in emulator

### PR DESCRIPTION
**Pull request by Trim21**
should fix #3090

### CODE REVIEW

File: ui/raidboss/popup-text.ts [hunk 1]
```diff
@@ -316,17 +316,22 @@ class TriggerOutputProxy {
...
+    let value: unknown;
+    if (typeof template === 'string')
+      // user config
+      value = template;
+    else
+      value = template[this.displayLang] ?? template['en'];
 
     if (typeof value !== 'string') {
-      console.error(`Trigger ${id} has invalid outputString ${name}.`);
+      console.error(`Trigger ${id} has invalid outputString ${name}.`, template);
```
Comment (valarnin) [inline ui/raidboss/popup-text.ts:334]: Might make sense to `JSON.stringify(template)` here, since otherwise I think OverlayPlugin's console log will just show `object`?

File: ui/raidboss/popup-text.ts [hunk 2]
```diff
@@ -316,17 +316,22 @@ class TriggerOutputProxy {
...
-      template: { [lang: string]: unknown } | undefined,
+      template: { [lang: string]: unknown } | string | undefined,
       params: TriggerParams,
       name: string,
       id: string): string | undefined {
     if (!template)
       return;
 
-    const value = template[this.displayLang] ?? template['en'];
+    let value: unknown;
```
Comment (Trim21) [inline ui/raidboss/popup-text.ts:326]: I this this could be shortcuted with `template[this.displayLang] ?? template['en'] ?? template`, but typechecking deny it.

**Comment by valarnin** [comment]
Just for clarity, what trigger produced this error to begin with? I feel like there's behavior here that doesn't match with the definitions in trigger.d.ts and if that's the case then that file should be updated as well?

**Comment by Trim21** [comment]
> Just for clarity, what trigger produced this error to begin with? I feel like there's behavior here that doesn't match with the definitions in trigger.d.ts and if that's the case then that file should be updated as well?

none of inner trigger report this…

but any trigger could.

`template` may be string that user set in config.html

**Comment by valarnin** [comment]
Yeah, I can reproduce the same way. So the definition of `OutputStrings` on `TriggerAutoConfig` is incorrect then I guess?

**Comment by Trim21** [comment]
Yes, I think it's wrong according to this bug.

**Comment by quisquous** [comment]
I think also at some point there were some triggers that just said `{ outputStrings: { key: 'text' } }` as well.  I think those have been udpated (or I just can't find them).

**Comment by valarnin** [comment]
> 
> 
> I think also at some point there were some triggers that just said `{ outputStrings: { key: 'text' } }` as well. I think those have been udpated (or I just can't find them).

A quick check via dev tools in raidemulator shows no entries that don't follow the correct format.

```js
testMatches = {
};
testData = {
};
window.raidEmulator.popupText.triggerSets.forEach((set) => {
  if (set.triggers) {
    set.triggers.forEach((t) => {
      if (t.outputStrings !== undefined) {
        window.raidEmulator.popupText.ProcessTrigger(t);
        let v;
        if (typeof t.outputStrings === 'function')
          v = t.outputStrings(testData, testMatches, t.output);
        else
          v = t.outputStrings;
        if (typeof v !== 'object' || (typeof v === 'object' && v === null))
          console.log(1, t, typeof v, v);
        else for (const k in v) {
          if (typeof v[k] !== 'object')
          	console.log(2, t, typeof v, v, typeof v[k], v[k]);
          else if (typeof v[k]['en'] !== 'string')
          	console.log(3, t, typeof v, v, typeof v[k], v[k], typeof v[k]['en'], v[k]['en']);
        }
      }
    });
  }
});
```
