### PR TITLE
raidemulator: Fix missing properties on getCombatants response

### LINKED ISSUE #2932: raidemulator broken with callOverlayHandler
## Description

e12s trigger `E12S Promise Chiseled Sculpture Tether`

https://github.com/quisquous/cactbot/blob/b4b25c83b3bd9a8f7e5ecb4b5263a1450a16420d/ui/raidboss/data/05-shb/raid/e12s.js#L430-L450

this used to be `output.unknown` in raidemulator. currently it's broken because `TypeError: Cannot read property 'toString' of undefined`

https://github.com/quisquous/cactbot/blob/b4b25c83b3bd9a8f7e5ecb4b5263a1450a16420d/ui/raidboss/data/05-shb/raid/e12s.js#L451-L458

should be fixed with 

```diff
diff --git a/ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js b/ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js
index 6a05adf2..fba9d206 100644
--- a/ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js
+++ b/ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js
@@ -28,14 +28,16 @@ export default class RaidEmulatorOverlayApiHook {
       return new Promise((res) => {
         const combatants = [];
 
-        for (const id in tracker.combatants) {
-          const combatant = tracker.combatants[id];
+        for (const [id, combatant] of Object.entries(tracker.combatants)) {
           // nextSignificantState is a bit inefficient but given that this isn't run every tick
           // we can afford to be a bit inefficient for readability's sake
-          const combatantState = combatant.nextSignificantState(timestamp).toPluginState();
+          const combatantState = {
+            ID: id,
+            ...combatant.nextSignificantState(timestamp).toPluginState(),
+          };
           if (msg.ids && msg.ids.includes(parseInt(id, 16)))
             combatants.push(combatantState);
-          else if (msg.names && msg.names.includes(tracker.combatants[id].name))
+          else if (msg.names && msg.names.includes(combatant.name))
             combatants.push(combatantState);
         }
         res({

```

@valarnin

### PR DESCRIPTION
**Pull request by valarnin**
Fix #2932

@Trim21 I can't test this right now to make sure it fixes the exact issue you described, but it should. Can you test and verify? Otherwise I can test in about 4 or 5 hours.

### CODE REVIEW

**Comment by Trim21** [comment]
works fine. Thanks

**Comment by Trim21** [comment]
would it be better readable like this?

```JS
        for (const [id, combatant] of Object.entries(tracker.combatants)) {
          // nextSignificantState is a bit inefficient but given that this isn't run every tick
          // we can afford to be a bit inefficient for readability's sake
          const combatantState = {
            ID: combatant.id,
            Name: combatant.name,
            Level: combatant.level,
            Job: combatant.job,
            ...combatant.nextSignificantState(timestamp).toPluginState(),
          };
```

**Comment by valarnin** [comment]
I don't know if that makes sense with the typescript conversion upcoming. This is in my current WIP for the next raidemulator typescript conversion pass:

```typescript

// Member names taken from OverlayPlugin's MiniParseEventSource.cs
// Types taken from FFXIV parser plugin
export interface IPluginState {
  CurrentWorldID?: number;
  WorldID?: number;
  WorldName?: string;
  BNpcID?: number;
  BNpcNameID?: number;
  PartyType?: number;
  ID?: number;
  OwnerID?: number;
  type?: number;
  Job?: number;
  Level?: number;
  Name?: string;
  CurrentHP: number;
  MaxHP: number;
  CurrentMP: number;
  MaxMP: number;
  PosX: number;
  PosY: number;
  PosZ: number;
  Heading: number;
}

export default class CombatantState implements ICombatantState {
...
  toPluginState(): IPluginState {
```

**Comment by Trim21** [comment]
> I don't know if that makes sense with the typescript conversion upcoming. This is in my current WIP for the next raidemulator typescript conversion pass:
> 
> ```ts
> // Member names taken from OverlayPlugin's MiniParseEventSource.cs
> // Types taken from FFXIV parser plugin
> export interface IPluginState {
>   CurrentWorldID?: number;
>   WorldID?: number;
>   WorldName?: string;
>   BNpcID?: number;
>   BNpcNameID?: number;
>   PartyType?: number;
>   ID?: number;
>   OwnerID?: number;
>   type?: number;
>   Job?: number;
>   Level?: number;
>   Name?: string;
>   CurrentHP: number;
>   MaxHP: number;
>   CurrentMP: number;
>   MaxMP: number;
>   PosX: number;
>   PosY: number;
>   PosZ: number;
>   Heading: number;
> }
> 
> export default class CombatantState implements ICombatantState {
> ...
>   toPluginState(): IPluginState {
> ```

should works fine with typescript



```ts
export interface IPluginState {
  CurrentWorldID?: number;
  WorldID?: number;
  WorldName?: string;
  BNpcID?: number;
  BNpcNameID?: number;
  PartyType?: number;
  ID?: number;
  OwnerID?: number;
  type?: number;
  Job?: number;
  Level?: number;
  Name?: string;
  CurrentHP: number;
  MaxHP: number;
  CurrentMP: number;
  MaxMP: number;
  PosX: number;
  PosY: number;
  PosZ: number;
  Heading: number;
}

declare const combatant: {
  id: number;
  name: string;
  level: number;
  job: number;
  toPluginState: () => {
    CurrentHP: number;
    MaxHP: number;
    CurrentMP: number;
    MaxMP: number;
    PosX: number;
    PosY: number;
    PosZ: number;
    Heading: number;
  };
};


export const combatantState: IPluginState = {
  ID: combatant.id,
  Name: combatant.name,
  Level: combatant.level,
  Job: combatant.job,
  ...combatant.toPluginState(),
};

```



<details><summary><b>Output</b></summary>

```ts
export const combatantState = Object.assign({ ID: combatant.id, Name: combatant.name, Level: combatant.level, Job: combatant.job }, combatant.toPluginState());

```


</details>


<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```


</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgSQAUAbAVwHNkBlGTVOAbwCg44BhUqKYFAdWmIATfABEA-AC44SUgFsARmgDcLOPyhDRk6XMVQVrdUIBymWcG0BnGFGTkDcAELGw2LVJkLlq569Pn3HS99VUJMWABPABUIsAsPXW9WQM89BwB5AHckNBTEkNYYWPigtNUAKQh5bVSkuAAZYAA3YGIa-Id-EutbJHtVDi4eGAAJQgTghwBZTBAxibLWQe4UKfHSupmQNYW6wghLAA1dgrh9ywBNE4dzgC1r1RHgTEE7B4BfJiZBYGxicLw2AgSGscCBCjomBQUmYrAQggerCQZmAUh6dgcxGarURcAAVlVcTAICQKNRaKgpAAKACUcAAvAA+RiqJacFajda1U6sLbzDY89js4Y7AUOXmzUXc8VnA7HMWs2WXXGsO4quBPF5vBWsd4qPVfJigSCwMHA0Hg+SQlA0OiogikyhIW30eks5IiKSW60wAB08IANKoul6IBDaChfcjzEHWI0WsRQ+GoX6sQnY3BKvIk1aI36CfIM77i96877iY7yXbaUGDUA)

**Comment by valarnin** [comment]
It's fine syntactically. I can't speak for the difference in readability here, they're both roughly the same to me.

I'm just not sure if it makes sense to clobber the type of the object to a generic there. With the addition of the typing on `const combatantState` I think this makes more sense, but it's not something that can be included in this PR.

Thoughts?

File: ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js [hunk 1]
```diff
@@ -33,11 +33,29 @@ export default class RaidEmulatorOverlayApiHook {
...
+          combatantState.Level = combatant.level;
+          combatantState.Job = combatant.job;
+          if ((msg.ids && msg.ids.length) || (msg.names && msg.names.length)) {
+            if (msg.ids && msg.ids.includes(parseInt(id, 16)))
+              combatants.push(combatantState);
+            else if (msg.names && msg.names.includes(tracker.combatants[id].name))
+              combatants.push(combatantState);
+          } else {
             combatants.push(combatantState);
+          }
```
Comment (quisquous) [inline ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js:47]:
```suggestion
          if (!msg.ids || !msg.names)
            combatants.push(combatantState);
          else if (msg.ids && msg.ids.includes(parseInt(id, 16)))
            combatants.push(combatantState);
          else if (msg.names && msg.names.includes(tracker.combatants[id].name))
            combatants.push(combatantState);
```

I think this would be clearer like this.

It seems like there's an additional logic fix that you're making here too, in that previously we would have pushed a combatant if an id was specified but it wasn't included.  However, I'm not sure that the `msg.ids.length` additional change makes sense to me?  As an edge case, if I specify `ids: []` I think I'd expect that to return nothing rather return everything.

File: ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js [hunk 2]
```diff
@@ -33,11 +33,29 @@ export default class RaidEmulatorOverlayApiHook {
           // nextSignificantState is a bit inefficient but given that this isn't run every tick
           // we can afford to be a bit inefficient for readability's sake
           const combatantState = combatant.nextSignificantState(timestamp).toPluginState();
-          if (msg.ids && msg.ids.includes(parseInt(id, 16)))
-            combatants.push(combatantState);
-          else if (msg.names && msg.names.includes(tracker.combatants[id].name))
+          combatantState.ID = combatant.id;
+          combatantState.Name = combatant.name;
+          combatantState.Level = combatant.level;
+          combatantState.Job = combatant.job;
```
Comment (quisquous) [inline ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js:39]: I think either this or Trim21's version is fine.  If there's a type issue, we can handle it when this file gets converted to TypeScript and it's clearer what the tradeoffs are.

Am I correct that this is the fix? There's a bunch of other changes going on, but this is fundamentally the fix?

File: ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js [hunk 3]
```diff
@@ -33,11 +33,29 @@ export default class RaidEmulatorOverlayApiHook {
...
+          if ((msg.ids && msg.ids.length) || (msg.names && msg.names.length)) {
+            if (msg.ids && msg.ids.includes(parseInt(id, 16)))
+              combatants.push(combatantState);
+            else if (msg.names && msg.names.includes(tracker.combatants[id].name))
+              combatants.push(combatantState);
+          } else {
             combatants.push(combatantState);
+          }
         }
+        // @TODO: Move this to track properly
```
Comment (quisquous) [inline ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js:49]: What do you mean by this TODO? Move this where?  Can this be done properly in this PR, or just postponed for another PR (as I don't think triggers use these fields)?

File: ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js (hunk 1 above)
Comment (valarnin) [reply ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js:47]: This is meant to copy the logic of the entire getCombatants filter in both of the following parts of MiniParseEventSource.cs:
https://github.com/ngld/OverlayPlugin/blob/master/OverlayPlugin.Core/EventSources/MiniParseEventSource.cs#L117-L135
https://github.com/ngld/OverlayPlugin/blob/master/OverlayPlugin.Core/EventSources/MiniParseEventSource.cs#L263-L289

Unless I'm misreading that code (it's been 15 months since I wrote it, apparently), if an empty array is submitted it's treated the same as if the array is completely omitted?

Comment (quisquous) [reply ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js:47]: Ok!  Thanks for the reference.

I still think not nesting a conditional makes the logic easier to read, at least.

Comment (valarnin) [reply ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js:47]: I don't know how to get around nesting the conditionals without making the first conditional really long. It would basically have to be something like this?

```javascript
          if ((!msg.ids || !msg.ids.length) && (!msg.names || !msg.names.length)) {
            combatants.push(combatantState);
          else if (msg.ids && msg.ids.includes(parseInt(id, 16)))
            combatants.push(combatantState);
          else if (msg.names && msg.names.includes(tracker.combatants[id].name))
            combatants.push(combatantState);
```

Maybe instead move this up in scope so it's something like:

```javascript
      return new Promise((res) => {
        const combatants = [];
        // If no ids and names, or both are empty, return all combatants
        const allCombatants = (!msg.ids || !msg.ids.length) && (!msg.names || !msg.names.length);

        for (const id in tracker.combatants) {
...
          if (allCombatants) {
            combatants.push(combatantState);
          else if (msg.ids && msg.ids.includes(parseInt(id, 16)))
            combatants.push(combatantState);
          else if (msg.names && msg.names.includes(tracker.combatants[id].name))
            combatants.push(combatantState);
```

File: ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js (hunk 3 above)
Comment (quisquous) [reply ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js:49]: Oh, right! I forgot about those triggers.  How hard is it to track rather than try to derive them afterwards?  That seems like a much better solution.  Can it be done here?

Comment (valarnin) [reply ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js:49]: I was thinking of adding the tracking as a follow up PR after #2936 gets merged.

File: ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js (hunk 1 above)
Comment (quisquous) [reply ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js:47]: What about:

```javascript
          const hasIds = msg.ids && msg.ids.length;
          const hasNames = msg.names && msg.names.length;
          if (!hasIds && !hasNames)
            combatants.push(combatantState);
          else if (hasIds && msg.ids.includes(parseInt(id, 16)))
            combatants.push(combatantState);
          else if (hasNames && msg.names.includes(tracker.combatants[id].name))
            combatants.push(combatantState);
```

Comment (valarnin) [reply ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js:47]: That also works, though I still think it makes sense to put those two `const` variables outside the for loop? No sense in checking them every iteration of the loop.

Comment (quisquous) [reply ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js:47]: Even better.  :+1:

File: ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js (hunk 3 above)
Comment (quisquous) [reply ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js:49]: Ok!

File: ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js (hunk 1 above)
Comment (valarnin) [reply ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js:47]: Hmm, this is functional but I'm not really a fan of the typing of the hasIds/hasNames vars?

image

Maybe make it more explicit?

```javascript
        const hasIds = msg.ids !== undefined && msg.ids.length > 0;
        const hasNames = msg.names !== undefined && msg.names.length > 0;
```

image

Comment (quisquous) [reply ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js:47]: Sounds good to me.

Comment (valarnin) [reply ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js]: This has been updated.

File: ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js (hunk 2 above)
Comment (valarnin) [reply ui/raidboss/emulator/overrides/RaidEmulatorOverlayApiHook.js]: Yes, this fixes Trim21's original issue. The other changes include a fix for other triggers as discussed on the comments below this one, and fixes to the logic to more closely match the OverlayPlugin implementation.
