### PR TITLE
raidemulator: Bug fixes

### LINKED ISSUE #3156: Emulator playback bug with _onTriggerInternalDelaySeconds
```
ReferenceError: Cannot access 'ret' before initialization
   at RaidEmulatorPopupText._onTriggerInternalDelaySeconds
```

It looks like the code is referring to `ret` inside of its own construction.  I'm not sure how to easily disentangle this, so filing a bug.

"repro" /airquotes

```diff
diff --git a/ui/raidboss/data/04-sb/raid/o3s.js b/ui/raidboss/data/04-sb/raid/o3
s.js
index c024f271..9e75ec36 100644
--- a/ui/raidboss/data/04-sb/raid/o3s.js
+++ b/ui/raidboss/data/04-sb/raid/o3s.js
@@ -57,8 +57,9 @@ export default {

         data.holyTargets = data.holyTargets || [];
         data.holyTargets.push(matches.target);
-        return data.holyTargets.length === 4;
+        return data.holyTargets.length === 2;
       },
+      delaySeconds: 0.5,
       alarmText: (data, _matches, output) => {
         if (data.holyTargets[1] !== data.me)
           return '';
```
[DeltascapeV30Savage_20210617_045039_2m3s_wipe.log](https://github.com/quisquous/cactbot/files/6690769/DeltascapeV30Savage_20210617_045039_2m3s_wipe.log)

### LINKED ISSUE #3157: Emulator bug showing sound instead of alertText in analyzed list
Use log from https://github.com/quisquous/cactbot/issues/3156#issue-926788664
Use patch from https://github.com/quisquous/cactbot/commit/dbde1ec4f6541fc1eea43aa831e16f73d6bd2a90

image
image

The alert works fine during playback.

### LINKED ISSUE #3158: Emulator hit UnreachableCode
image

Repro: https://github.com/quisquous/cactbot/commit/ce82211c8e27fbab9f4ffe3318434d1f81ee57db
Log: [DeltascapeV20Savage_20210617_043639_7m38s.log](https://github.com/quisquous/cactbot/files/6691004/DeltascapeV20Savage_20210617_043639_7m38s.log)

### PR DESCRIPTION
**Pull request by valarnin**
fix #3156
fix #3157
fix #3158

### CODE REVIEW

File: ui/raidboss/emulator/data/AnalyzedEncounter.ts [hunk 1]
```diff
@@ -147,11 +147,19 @@ export default class AnalyzedEncounter extends EventBus {
...
+
         const resolver = popupText.currentResolver = new Resolver({
           initialData: EmulatorCommon.cloneData(popupText.getData()),
           suppressed: false,
           executed: false,
         });
+        resolver.triggerHelper =
+          popupText._onTriggerInternalGetHelper(
+              trigger,
+              matches?.groups as never,
```
Comment (quisquous) [inline ui/raidboss/emulator/data/AnalyzedEncounter.ts:161]: What about

```suggestion
              matches?.groups ?? {},
```

Is `as never` functioning here like `as any` with a different name?

**Comment by quisquous** [comment]
Thanks for this.  In the future, would you mind one PR per bugfix and not smushing them all together?  Reasoning here is mostly that it makes future archaeology harder (oh here's this line of code, what was it fixing? oh it's one of any of these three bugs?), reverting harder, and makes the changelog of commits less useful to read.

**Comment by valarnin** [comment]
> 
> 
> Thanks for this. In the future, would you mind one PR per bugfix and not smushing them all together? Reasoning here is mostly that it makes future archaeology harder (oh here's this line of code, what was it fixing? oh it's one of any of these three bugs?), reverting harder, and makes the changelog of commits less useful to read.

I didn't want to do three separate PRs that might conflict with each other, so instead I put each fix on its own commit. I was hoping the `git blame` would show the commit message for each location which would have had the issue # in it, but apparently it doesn't?
