### PR TITLE
fisher: fix place and fish regex

### LINKED ISSUE #3998: Fisher: Overlay issue with certain Ultima Thule fishing holes
Description

I noticed that the overlay seems to 'hang' and not display the usual rolling timer on some fishing holes. In most cases, it will display normally while the spot is 'unidentified fishing hole', but once the name is revealed, the timer freezes and doesn't update for that hole again.

I've managed to isolate it to a few fishing spots in Ultima Thule, all of which are using Greek letters (α, β, γ).
For example, the timer for Limne 18 displays fine, but Limne 3-α does not - or 3-β, apohelos 18-β, etc etc. It displays normally while any of these were 'unidentified', but once the name was revealed with the Greek lettering, the overlay seemed to not know what to do with it.

At the time of this report, the last update hasn't fixed it, so I think it simply slipped through. My ACT parsing language is set to English, as well. ACT logs look normal on the "you cast your line at [fishing hole] chat messages as well, and ACT's as up to date as can be.

I unfortunately can't seem to provide any screenshots of the 'frozen' overlay either, because...the timer just doesn't show up on the affected locations. I guess the plugin doesn't even recognize that I'm at a viable fishing spot due to the potential name-reading issue.

I'd be happy to provide any other info I can, if for some reason this bug isn't able to be duplicated. Thanks!

Edit for additional info: the debug log under OverlayPlugin.dll in ACT (I was fishing at Limne 3-β) :
"[1/8/2022 5:23:24 AM] Info: Fisher: BrowserConsole: placemissing in catch (Source: file:///C:/Users/Drago/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot-0.16.5/cactbot/ui/fisher/fisher.bundle.js, Line: 13303)
[1/8/2022 5:23:29 AM] Info: Fisher: BrowserConsole: failed to look up place: [object Object] (Source: file:///C:/Users/Drago/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot-0.16.5/cactbot/ui/fisher/fisher.bundle.js, Line: 13376)
[1/8/2022 5:23:29 AM] Info: Fisher: BrowserConsole: failed to look up place: [object Object] (Source: file:///C:/Users/Drago/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot-0.16.5/cactbot/ui/fisher/fisher.bundle.js, Line: 13376)"

### PR DESCRIPTION
**Pull request by Bing-su**
may fix #3998?

change `place` regex to `.+` for sure, and added `αβγ` for uncertain.

fix `fish` regex for `'36519': 'E.B.E-9318',` and `'33243': '隆卡的大水蛇？', 'Grand Serpent marin de Ronka?' ...`

### CODE REVIEW

**Comment by quisquous** [comment]
Thanks for this.  I'll try to test it shortly to see if it fixes that issue.

File: ui/fisher/fisher.js [hunk 1]
```diff
@@ -75,7 +75,7 @@ class Fisher {
         cast: NetRegexes.gameLog({
           code: '08c3',
           line:
-            '(?:[\\w\']\\.?)(?:[\\w\'\\s]+\\.?)? cast(?:s?) (?:your|his|her) line (?:on|in|at) (?:the )?(?<place>[\\w\\s\'&()]+)\\..*?',
+            '(?:[\\w\']\\.?)(?:[\\w\'\\s]+\\.?)? cast(?:s?) (?:your|his|her) line (?:on|in|at) (?:the )?(?<place>.+)\\..*?',
```
Comment (quisquous) [inline ui/fisher/fisher.js:78]: I think this is ok because no fishing locations (currently) have a `.` in them, and so the `\\.` will always catch the end of the fishing place.

**Comment by quisquous** [comment]
This fixes #3998 for me.  Thank you!
