### PR TITLE
raidboss: Fix timeline sync based on area seal message

### LINKED ISSUE #3040: Raidboss: No timelines in some content
In the last few days i noticed that for some contents (e.g. Delubrum normal, Nier raid Nr.3) i do not have timelines anymore (alerts are working fine). 
In other content (e.g. Uwu, Titan Ex, test timelines in limsa) its working fine

For myself i am using the latest nightly build (self compiled) and a friend of mine uses the latest official distributed version (upgraded through ACT itself)

Following is the Overlayplugin output: 
```
[08.06.2021 08:56:23] Info: AssemblyResolver: Loaded: Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
[08.06.2021 08:56:24] Info: AssemblyResolver: Loaded: websocket-sharp, Version=1.0.2.32519, Culture=neutral, PublicKeyToken=5660b08a1845a91e
[08.06.2021 08:56:24] Info: AssemblyResolver: Loaded: HtmlRenderer, Version=0.16.6.0, Culture=neutral, PublicKeyToken=null
[08.06.2021 08:56:24] Info: AssemblyResolver: Loaded: CefSharp, Version=75.1.141.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138
[08.06.2021 08:56:24] Info: InitPlugin: PluginDirectory = E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld
[08.06.2021 08:56:24] Info: AssemblyResolver: Loaded: CefSharp.OffScreen, Version=75.1.141.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138
[08.06.2021 08:56:24] Info: AssemblyResolver: Loaded: CefSharp.Core, Version=75.1.141.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138
[08.06.2021 08:56:24] Info: AssemblyResolver: Loaded: OverlayPlugin.Core.resources, Version=0.16.6.0, Culture=de-DE, PublicKeyToken=null
[08.06.2021 08:56:24] Info: InitPlugin: Initialised.
[08.06.2021 08:56:32] Info: cactbot: 0.22.7.0 E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\CactbotOverlay.dll (dir: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot)
[08.06.2021 08:56:32] Info: OverlayPlugin: 0.16.6.0 E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\OverlayPlugin.dll
[08.06.2021 08:56:32] Info: FFXIV Plugin: 2.0.9.7 E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\FFXIV_ACT_Plugin.dll
[08.06.2021 08:56:32] Info: ACT: 3.5.0.273 E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Advanced Combat Tracker.exe
[08.06.2021 08:56:32] Info: Parsing Plugin Language: de
[08.06.2021 08:56:32] Info: System Locale: de-DE
[08.06.2021 08:56:32] Info: cactbot user directory: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\user
[08.06.2021 08:56:32] Info: Version: intl
[08.06.2021 08:56:32] Info: LoadAddons: CactbotOverlay.dll: Initialized Cactbot.PluginLoader
[08.06.2021 08:56:32] Info: AssemblyResolver: Loaded: Markdig.Signed, Version=0.18.3.0, Culture=neutral, PublicKeyToken=870da25a133885f8
[08.06.2021 08:56:33] Info: WS: Warn: The current logging level has been changed to Info. 
[08.06.2021 08:56:33] Info: AssemblyResolver: Loaded: OverlayPlugin.Updater.resources, Version=0.16.6.0, Culture=de-DE, PublicKeyToken=null
[08.06.2021 08:56:34] Info: zeffui: BrowserConsole: ZeffUI fully loaded. (Source: https://zeffuro.github.io/ZeffUI/scripts/index.js, Line: 93)
[08.06.2021 08:56:34] Info: timeline: BrowserConsole: local user file: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\user\raidboss\a8s.js (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 2793)
[08.06.2021 08:56:34] Info: timeline: BrowserConsole: local user file: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\user\raidboss\bluemage.js (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 2793)
[08.06.2021 08:56:34] Info: timeline: BrowserConsole: local user file: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\user\raidboss\diamond.js (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 2793)
[08.06.2021 08:56:34] Info: timeline: BrowserConsole: local user file: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\user\raidboss\e4s.js (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 2793)
[08.06.2021 08:56:34] Info: timeline: BrowserConsole: local user file: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\user\raidboss\e6s.js (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 2793)
[08.06.2021 08:56:34] Info: timeline: BrowserConsole: local user file: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\user\raidboss\sastasha.js (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 2793)
[08.06.2021 08:56:34] Info: timeline: BrowserConsole: local user file: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\user\raidboss\t13.js (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 2793)
[08.06.2021 08:56:34] Info: timeline: BrowserConsole: local user file: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\user\raidboss\t9.js (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 2793)
[08.06.2021 08:56:34] Info: timeline: BrowserConsole: local user file: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\user\raidboss\uwu.js (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 2793)
[08.06.2021 08:56:34] Info: timeline: BrowserConsole: local user file: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\user\raidboss.js (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 2793)
[08.06.2021 08:56:34] Info: timeline: BrowserConsole: local user file: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\user\raidboss.css (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 2793)
[08.06.2021 08:56:34] Info: zeffui: BrowserConsole: Uncaught (in promise) TypeError: Cannot read property 'PartyType' of undefined (Source: https://zeffuro.github.io/ZeffUI/scripts/index.js, Line: 1686)
[08.06.2021 08:56:35] Info: timeline: BrowserConsole: Loading 00-misc/general.js (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 13850)
[08.06.2021 08:56:39] Info: Found enmity memory for 5.5.
[08.06.2021 08:57:34] Info: OverlayControl: local user file: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\user\raidboss\a8s.js (file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/config/config.bundle.js)
[08.06.2021 08:57:34] Info: OverlayControl: local user file: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\user\raidboss\bluemage.js (file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/config/config.bundle.js)
[08.06.2021 08:57:34] Info: OverlayControl: local user file: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\user\raidboss\diamond.js (file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/config/config.bundle.js)
[08.06.2021 08:57:34] Info: OverlayControl: local user file: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\user\raidboss\e4s.js (file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/config/config.bundle.js)
[08.06.2021 08:57:34] Info: OverlayControl: local user file: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\user\raidboss\e6s.js (file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/config/config.bundle.js)
[08.06.2021 08:57:34] Info: OverlayControl: local user file: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\user\raidboss\sastasha.js (file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/config/config.bundle.js)
[08.06.2021 08:57:34] Info: OverlayControl: local user file: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\user\raidboss\t13.js (file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/config/config.bundle.js)
[08.06.2021 08:57:34] Info: OverlayControl: local user file: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\user\raidboss\t9.js (file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/config/config.bundle.js)
[08.06.2021 08:57:34] Info: OverlayControl: local user file: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\user\raidboss\uwu.js (file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/config/config.bundle.js)
[08.06.2021 08:57:34] Info: OverlayControl: local user file: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\user\raidboss.js (file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/config/config.bundle.js)
[08.06.2021 08:57:34] Info: OverlayControl: local user file: E:\FINAL FANTASY XIV - A Realm Reborn\AdditionalExtern\ACT\Plugins\OverlayPlugin_ngld\cactbot\user\raidboss.css (file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/config/config.bundle.js)
[08.06.2021 10:01:15] Info: timeline: BrowserConsole: Loading 00-misc/general.js (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 13850)
[08.06.2021 10:01:19] Info: timeline: BrowserConsole: Loading 00-misc/general.js (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 13850)
[08.06.2021 10:01:29] Info: timeline: BrowserConsole: Loading 00-misc/general.js (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 13850)
[08.06.2021 10:01:38] Info: timeline: BrowserConsole: Loading 00-misc/general.js (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 13850)
[08.06.2021 10:12:43] Info: timeline: BrowserConsole: Loading 00-misc/general.js (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 13850)
[08.06.2021 10:12:43] Info: timeline: BrowserConsole: Loading 05-shb/alliance/the_tower_at_paradigms_breach.js (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 13850)
[08.06.2021 10:52:27] Info: timeline: BrowserConsole: Loading 00-misc/general.js (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 13850)
[08.06.2021 11:13:32] Info: timeline: BrowserConsole: Loading 00-misc/general.js (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 13850)
[08.06.2021 11:13:32] Info: timeline: BrowserConsole: Loading 05-shb/eureka/delubrum_reginae.js (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 13850)
[08.06.2021 11:53:40] Info: timeline: BrowserConsole: Loading 00-misc/general.js (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 13850)
[08.06.2021 11:55:53] Info: timeline: BrowserConsole: Loading 00-misc/general.js (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 13850)
[08.06.2021 11:55:53] Info: timeline: BrowserConsole: Loading 00-misc/test.js (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 13850)
[08.06.2021 11:56:49] Info: timeline: BrowserConsole: Loading 00-misc/general.js (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 13850)
[08.06.2021 11:56:49] Info: timeline: BrowserConsole: Loading 02-arr/trial/titan-ex.ts (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 13850)
[08.06.2021 11:58:10] Info: timeline: BrowserConsole: Loading 00-misc/general.js (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 13850)
[08.06.2021 11:58:10] Info: timeline: BrowserConsole: Loading 00-misc/test.js (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_ngld/cactbot/ui/raidboss/raidboss.bundle.js, Line: 13850)

```

### PR DESCRIPTION
**Pull request by valarnin**
This should, I think, fix #3040.

Please review this one more thoroughly, as I'm not as familiar with exactly how common replacements work through all the components.

The fix looks good in raidemulator using the log attached to the issue, at least.

### CODE REVIEW

File: ui/raidboss/common_replacement.ts [hunk 1]
```diff
@@ -5,7 +5,7 @@ import { Lang, NonEnLang } from 'resources/languages';
 // It's awkward to refer to these string keys, so name them as replaceSync[keys.sealKey].
 export const syncKeys = {
   // Match Regexes, NetRegexes, and timeline constructions of seal log lines.
-  seal: '(?<=00:0839:|00.*0839.*\\\\\|)(.*) will be sealed off(?: in (?:[0-9]+ seconds)?)?',
+  seal: '(?<=00:0839:|00\\|0839\\|)(.*) will be sealed off(?: in (?:[0-9]+ seconds)?)?',
```
Comment (quisquous) [inline ui/raidboss/common_replacement.ts:8]: Is this really a correct match for NetRegexes? Game logs are `00|timestamp|0839|blah will be sealed off|hash`.

Comment (valarnin) [reply ui/raidboss/common_replacement.ts:8]: So it should be this instead?

```ts
  seal: '(?<=00:0839:|00\\|[^|]*\\|0839\\|)(.*) will be sealed off(?: in (?:[0-9]+ seconds)?)?',
```

Comment (quisquous) [reply ui/raidboss/common_replacement.ts:8]:
```diff
-seal: '(?<=00:0839:|00\\|[^|]*\\|0839\\|)(.*) will be sealed off(?: in (?:[0-9]+ seconds)?)?',
+seal: '(?<=00:0839:|00\\|[^|]*\\|0839\\|\\|)(.*) will be sealed off(?: in (?:[0-9]+ seconds)?)?',
```

I think with one extra bar? I thought find-translations would balk at this, but I can't seem to.  I should probably write a common replacement unit test that verifies that this works properly with replacements for both kinds of regexes.

Comment (valarnin) [reply ui/raidboss/common_replacement.ts:8]: Looks good. I'll get this updated.

image
